name: Build APK
on: [workflow_call, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 
